INSERT INTO article(title,content) VALUES ('가가가가','1111');
INSERT INTO article(title,content) VALUES ('나나나나','2222');
INSERT INTO article(title,content) VALUES ('다다다다','3333');
INSERT INTO article(title,content) VALUES ('당신의 인생 영화는?','댓글 고');
INSERT INTO article(title,content) VALUES ('당신의 소울 푸드는?','댓글 고고');
INSERT INTO article(title,content) VALUES ('당신의 취미는?','댓글 고고고');
INSERT INTO comment(article_id,nickname,body) VALUES (4,'P','영화1');
INSERT INTO comment(article_id,nickname,body) VALUES (4,'K','영화2');
INSERT INTO comment(article_id,nickname,body) VALUES (4,'C','영화3');
INSERT INTO comment(article_id,nickname,body) VALUES (5,'P','치킨');
INSERT INTO comment(article_id,nickname,body) VALUES (5,'K','샤브샤브');
INSERT INTO comment(article_id,nickname,body) VALUES (5,'C','초밥');
INSERT INTO comment(article_id,nickname,body) VALUES (6,'P','조깅');
INSERT INTO comment(article_id,nickname,body) VALUES (6,'K','유튜브 시청');
INSERT INTO comment(article_id,nickname,body) VALUES (6,'C','독서');